@startuml deleteListId

autonumber "[0]"
hide footbox

participant "フロント" as front
participant "API" as api
participant "Firebase" as firebase
participant "RDS" as RDS

|||
front -> api : DELETE /list/{portfolioId}

opt 認証チェック
  api -> firebase: Tokenの確認
  front <-- api : UNAUTHORIZED(401)
end

opt バリデーションチェック
  front <-- api : Bad Request(400)
end

opt 削除対象チェック
  front <-- api : Not Found(404)
end

api  -> RDS : データ削除

front <-- api : 204を返す

@enduml