@startuml postList

autonumber "[0]"
hide footbox

participant "フロント" as front
participant "API" as api
participant "Firebase" as firebase
participant "S3" as s3
participant "RDS" as RDS

|||
front -> api : POST /list

opt 認証チェック
  api -> firebase: Tokenの確認
  front <-- api : UNAUTHORIZED(401)
end

opt バリデーションチェック
  front <-- api : Bad Request(400)
end

api -> s3 : 画像保存

api -> RDS : データ登録

front <-- api : 200を返す

@enduml